plugins {
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.graalvm.buildtools.native' version '0.10.5'
    id "com.diffplug.spotless" version "7.0.4"
}

subprojects {

    if (it.name == "platform") {
        return;
    }

    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'pmd'
    apply plugin: 'checkstyle'
    apply plugin: 'com.diffplug.spotless'

    repositories {
        mavenLocal()
        maven { url "https://maven.aliyun.com/nexus/content/groups/public" }
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    ext {
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter'
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        implementation 'org.mapstruct:mapstruct:1.5.3.Final'
        annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'

        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        api platform(project(':platform'))

        constraints {
            implementation 'com.mysql:mysql-connector-j:9.2.0'
        }
    }

    clean{
        delete "bin", "out", ".settings", ".classpath", ".project"
    }

    test {
        useJUnitPlatform()
    }


    pmd {
        consoleOutput = true
        rulesMinimumPriority = 5
        ruleSetFiles = files(rootProject.rootDir.getPath() + '/specification/pmd/ruleset.xml')
        ruleSets = []
    }

    spotless {
        java {
            removeUnusedImports()
            trimTrailingWhitespace()
            leadingTabsToSpaces(4)

            palantirJavaFormat()
            formatAnnotations()
        }
    }

    checkstyle {
        toolVersion = "10.12.4"
        config = rootProject.resources.text.fromFile("${rootProject.rootDir.getPath()}/specification/style/checkstyle.xml")
    }

}

tasks.withType(Wrapper) {
    enabled = false
}
