plugins {
    id("java-platform")
}

javaPlatform {
    allowDependencies()
}

dependencies {
    api platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    api platform("org.springframework.ai:spring-ai-bom:1.0.0")

    constraints {
        api("com.google.guava:guava:30.1-jre")
        api("org.apache.commons:commons-lang3:3.12.0")

        api("org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4")
        api("jakarta.validation:jakarta.validation-api:3.1.1")

        api('org.joda:joda-money:2.0.0')
        api("org.jadira.usertype:usertype.core:7.0.0.CR1")
    }
}