server:
  port: 8888

mybatis:
  type-aliases-package: me.warriorg.dubbo.model
  mappper-locations: classpath:me.warriorg.dubbo.springboot.dao/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379

  cache:
    type: redis
    cache-names: realTimeCache

  # <dubbo:application/>
  application:
    name: 11-provider-springboot

dubbo:
  application:
    name: 11-provider-springboot
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: me.warriorg.dubbo.springboot.service
