mybatis:
#  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: me.warriorg.spring.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true